# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.14"
  jobs:
    post_install:
      - pip install "poetry>=2,<3"
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --only docs

sphinx:
  configuration: docs/conf.py
