# Generated by Django 2.1 on 2018-08-26 18:54

from datetime import date, datetime, time, timezone

from django.db import migrations


def insert_demo_event(apps, schema_editor):
    Event = apps.get_model("myapp", "Event")
    event = Event(pk=1)
    event.name = "Event 01"
    event.start_date = date(2023, 1, 15)
    event.end_date = date(2023, 1, 20)
    event.start_time = time(4, 15)
    event.end_time = time(8, 25)
    event.start_datetime = datetime(2023, 3, 15, 4, 15, tzinfo=timezone.utc)
    event.end_datetime = datetime(2023, 3, 20, 8, 25, tzinfo=timezone.utc)
    event.start_month = date(2023, 2, 1)
    event.end_month = date(2023, 7, 1)
    event.start_year = date(2021, 1, 1)
    event.end_year = date(2023, 1, 1)
    event.save()


def reverse_insert_demo_event(apps, schema_editor):
    Event = apps.get_model("myapp", "Event")
    Event.objects.filter(name="Event 01").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insert_demo_event, reverse_code=reverse_insert_demo_event),
    ]
