# Generated by Django 2.1 on 2018-08-26 18:54

from datetime import datetime

from django.db import migrations


def insert_demo_event(apps, schema_editor):
    Event = apps.get_model("myapp", "Event")
    event = Event()
    event.name = "Event 01"
    event.start_date = datetime.now()
    event.end_date = datetime.now()
    event.start_time = datetime.now()
    event.end_time = datetime.now()
    event.start_datetime = datetime.now()
    event.end_datetime = datetime.now()
    event.start_month = datetime.now()
    event.end_month = datetime.now()
    event.start_year = datetime.now()
    event.end_year = datetime.now()
    event.save()


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insert_demo_event),
    ]
